name: Build ISO

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install tools
      run: make prep
    - name: Install grub
      run: make Install-Grub-BIOS
    - name: make move
      run: make move
      
    - name: Upload Build files
      uses: actions/upload-artifact@v2
      with: 
        name: SectorOS_Artifact-Build
        path: Build_files
        
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: Automatic Release Commit
        files: |
          Build_files/*.iso
          Build_files/*.bin
