name: Build ISO [There will be unstable builds which are not tested]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install tools
      run: sudo apt install xorriso && sudo apt install grub-common mtools
    - name: make clean
      run: make clean
      
    - name: Upload Build files
      uses: actions/upload-artifact@v2
      with: 
        name: SectorOS_Artifact-Build
        path: Build_files

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
          This release is automatically made
          draft: false
          prerelease: false
