on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_stable:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install tools
      run: make prep
    - name: make move
      run: make move GRUB=pt
      
    - name: Upload Build files
      uses: actions/upload-artifact@v2
      with: 
        name: SectorOS_ISO
        path: Build_files/SectorOS.iso

    - name: Upload Build files
      uses: actions/upload-artifact@v2
      with: 
        name: SectorOS_Kernel
        path: Build_files/SectorOS_Kernel.bin