name: Build ISO [There will be unstable builds which are not tested]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install tools
      run: sudo apt install xorriso && sudo apt install grub-common mtools
    - name: make clean
      run: make clean
      
    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: SectorOS_Artifact-Build
        path: Build_files
